#ifndef METLIBS_PUTOOLS_VERSION_H
#define METLIBS_PUTOOLS_VERSION_H

#define METLIBS_PUTOOLS_VERSION_MAJOR 5
#define METLIBS_PUTOOLS_VERSION_MINOR 1
#define METLIBS_PUTOOLS_VERSION_PATCH 1

#define METLIBS_PUTOOLS_VERSION_INT(major,minor,patch) \
    (1000000*major + 1000*minor + patch)
#define METLIBS_PUTOOLS_VERSION_CURRENT_INT \
    MIFI_VERSION_INT(MIFI_VERSION_MAJOR, MIFI_VERSION_MINOR, MIFI_VERSION_PATCH)

#endif // METLIBS_PUTOOLS_VERSION_H
